version: '3.7'

# This creates a container, uses our dockerfile we created, 
# and runs the build step (see the target)
services:
  ts-node-docker:
    build:
      context: .
      dockerfile: ./api/Dockerfile
      target: base
    volumes:
      - ./api/src:/home/node/app/src
      - ./api/nodemon.json:/home/node/app/nodemon.json
    container_name: ts-node-docker
    expose:
      - '4000'
    ports:
      - '4000:4000'
    command: npm run dev