version: '3.7'

services:
  node-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/home/node/app/src
      - ./nodemon.json:/home/node/app/nodemon.json
    container_name: node-api
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run dev